// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HeaderController from "./header_controller"
application.register("header", HeaderController)

import MapController from "./map_controller"
application.register("map", MapController)

import NewListingController from "./new_listing_controller"
application.register("new-listing", NewListingController)
